"""Publish a generated CLI to GitHub and PyPI.

`ducktap publish <name>` orchestrates the full release workflow:
1. Run shipcheck against the generated CLI.
2. Ensure a git repository is initialized and committed.
3. Create/push to a GitHub repo via `gh`.
4. Build a wheel/sdist via `python -m build`.
5. Upload to PyPI via `twine`.
"""
from __future__ import annotations

import shutil
import subprocess
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

from ducktap.verify.shipcheck import shipcheck


@dataclass
class StepResult:
    name: str
    ok: bool
    cmd: str = ""
    stdout: str = ""
    stderr: str = ""


@dataclass
class PublishResult:
    success: bool
    steps: list[StepResult] = field(default_factory=list)
    message: str = ""


RunCmd = Callable[[list[str], str | None], tuple[int, str, str]]


def _default_run(cmd: list[str], cwd: str | None = None) -> tuple[int, str, str]:
    result = subprocess.run(
        cmd, cwd=cwd, capture_output=True, text=True, check=False,
    )
    return result.returncode, result.stdout.strip(), result.stderr.strip()


def _which(tool: str) -> bool:
    return shutil.which(tool) is not None


def _step(
    name: str,
    cmd: list[str],
    cwd: str | None,
    run: RunCmd,
    required: bool = True,
) -> StepResult:
    rc, out, err = run(cmd, cwd)
    ok = rc == 0
    if required and not ok:
        return StepResult(
            name=name,
            ok=False,
            cmd=" ".join(cmd),
            stdout=out,
            stderr=err,
        )
    return StepResult(
        name=name,
        ok=True,
        cmd=" ".join(cmd),
        stdout=out,
        stderr=err,
    )


def publish(
    name: str,
    out_dir: str = "./out",
    github: bool = True,
    pypi: bool = True,
    dry_run: bool = False,
    private: bool = False,
    skip_shipcheck: bool = False,
    run: RunCmd | None = None,
) -> PublishResult:
    """Publish a generated CLI package.

    Parameters
    ----------
    name:
        Short API name used during `ducktap press` (e.g. ``petstore``).
    out_dir:
        Directory where `ducktap press` wrote artifacts.
    github:
        Create/push to a GitHub repository.
    pypi:
        Build and upload to PyPI.
    dry_run:
        Print what would be done without running external commands.
    private:
        Create a private GitHub repo instead of public.
    skip_shipcheck:
        Skip the structural sanity checks.
    run:
        Override for subprocess injection (testing).
    """
    runner = run or _default_run
    steps: list[StepResult] = []
    cli_dir = Path(out_dir) / f"{name}-dt-cli"

    if not cli_dir.exists():
        return PublishResult(
            success=False,
            message=f"Generated CLI not found: {cli_dir}",
        )

    # 1. shipcheck
    if not skip_shipcheck:
        checks = shipcheck(str(out_dir), name)
        failed = [c for c in checks if not c.passed]
        ok = not failed
        steps.append(
            StepResult(
                name="shipcheck",
                ok=ok,
                cmd=f"shipcheck({out_dir}, {name})",
                stderr="; ".join(f"{c.name}: {c.detail}" for c in failed) if failed else "OK",
            )
        )
        if not ok:
            return PublishResult(
                success=False,
                steps=steps,
                message=f"Shipcheck failed: {failed[0].name} — {failed[0].detail}",
            )

    # 2. git init + commit
    git_dir = cli_dir / ".git"
    if not git_dir.exists():
        steps.append(_step("git_init", ["git", "init"], str(cli_dir), runner))
        if not steps[-1].ok:
            return PublishResult(success=False, steps=steps, message="git init failed")
    else:
        steps.append(StepResult(name="git_init", ok=True, stdout="already initialised"))

    steps.append(
        _step("git_add", ["git", "add", "."], str(cli_dir), runner, required=False)
    )
    steps.append(
        _step(
            "git_commit",
            ["git", "commit", "-m", "chore: publish generated CLI via DuckTap"],
            str(cli_dir),
            runner,
            required=False,
        )
    )

    # 3. GitHub
    if github:
        if not _which("gh"):
            return PublishResult(
                success=False,
                steps=steps,
                message="`gh` (GitHub CLI) is not installed. Install it from https://cli.github.com",
            )

        repo_name = f"{name}-dt-cli"
        create_cmd = [
            "gh", "repo", "create", repo_name,
            "--description", f"Agent-native CLI for {name} (generated by DuckTap)",
            "--source", str(cli_dir),
            "--push",
        ]
        if private:
            create_cmd.append("--private")
        else:
            create_cmd.append("--public")

        steps.append(_step("gh_repo_create", create_cmd, str(cli_dir), runner, required=False))
        if not steps[-1].ok:
            # It may already exist; try pushing to existing remote
            steps.append(
                _step(
                    "git_push",
                    ["git", "push", "-u", "origin", "HEAD"],
                    str(cli_dir),
                    runner,
                    required=False,
                )
            )

    # 4. PyPI
    if pypi:
        if not _which("python"):
            return PublishResult(
                success=False,
                steps=steps,
                message="`python` not found in PATH",
            )
        if not _which("twine"):
            return PublishResult(
                success=False,
                steps=steps,
                message="`twine` is not installed. Install it with: pip install twine",
            )

        # build
        build_cmd = [shutil.which("python") or "python", "-m", "build"]
        steps.append(_step("python_build", build_cmd, str(cli_dir), runner))
        if not steps[-1].ok:
            return PublishResult(
                success=False, steps=steps, message="Build failed; not uploading to PyPI."
            )

        # upload
        upload_cmd = ["twine", "upload", "dist/*"]
        if dry_run:
            upload_cmd.append("--dry-run")
        steps.append(_step("twine_upload", upload_cmd, str(cli_dir), runner))
        if not steps[-1].ok:
            return PublishResult(
                success=False,
                steps=steps,
                message=f"PyPI upload failed: {steps[-1].stderr}",
            )

    return PublishResult(
        success=True,
        steps=steps,
        message="Publish workflow complete.",
    )
